export const FETCH_ADS_START = "FETCH_ADS_START";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAIL = "FETCH_ADS_FAIL";
export const INIT_FETCHED_ADS= "INITIAL_FETCHED_ADS";
export const SET_FETCHING_URL= "SET_FETCHING_URL";

export const FETCH_BRANDS_START = "FETCH_BRANDS_START";
export const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
export const FETCH_BRANDS_FAIL = "FETCH_BRANDS_FAIL";

export const FETCH_TYPES_START = "FETCH_TYPES_START";
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAIL = "FETCH_TYPES_FAIL";

export const CREATE_AD_START = "CREATE_AD_START";
export const CREATE_AD_SUCCESS = "CREATE_AD_SUCCESS";
export const CREATE_AD_FAIL = "CREATE_AD_FAIL";

export const FETCH_AD_START = "FETCH_AD_START";
export const FETCH_AD_SUCCESS = "FETCH_AD_SUCCESS";
export const FETCH_AD_FAIL = "FETCH_AD_FAIL";

export const FETCH_USER_ADS_START = "FETCH_USER_ADS_START";
export const FETCH_USER_ADS_SUCCESS = "FETCH_USER_ADS_SUCCESS";
export const  FETCH_USER_ADS_FAIL = "FETCH_USER_ADS_FAIL";


export const FETCH_AD_DETAILS_START = "FETCH_AD_DETAILS_START";
export const FETCH_AD_DETAILS_SUCCESS = "FETCH_AD_DETAILS_SUCCESS";
export const FETCH_AD_DETAILS_FAIL = "FETCH_AD_DETAILS_FAIL";

export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const READ_MESSAGE_FAIL = "READ_MESSAGE_FAIL";
export const READ_MESSAGE_START = "READ_MESSAGE_START";

export const FETCH_MESSAGE_PARTNERS_START = "FETCH_MESSAGE_PARTNERS_START";
export const FETCH_MESSAGE_PARTNERS_SUCCESS = "FETCH_MESSAGE_PARTNERS_SUCCESS";
export const FETCH_MESSAGE_PARTNERS_FAIL = "FETCH_MESSAGE_PARTNERS_FAIL";

export const FETCH_MESSAGES_START = "FETCH_MESSAGES_START";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAIL = "FETCH_MESSAGES_FAIL";

export const CREATE_RATE_START = "CREATE_RATE_START";
export const CREATE_RATE_SUCCESS = "CREATE_RATE_SUCCESS";
export const CREATE_RATE_FAIL = "CREATE_RATE_FAIL";

export const FETCH_RATE_LABELS_START = "FETCH_RATE_LABELS_START";
export const FETCH_RATE_LABELS_FAIL = "FETCH_RATE_LABELS_FAIL";
export const FETCH_RATE_LABELS_SUCCESS = "FETCH_RATE_LABELS_SUCCESS";

export const FETCH_FULL_RATE_START = "FETCH_FULL_RATE_START";
export const FETCH_FULL_RATE_SUCCESS = "FETCH_FULL_RATE_SUCCESS";
export const FETCH_FULL_RATE_FAIL = "FETCH_FULL_RATE_FAIL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CURRENCY_SELECTED = "CURRENCY_SELECTED";